-- Populate sample team members
INSERT INTO public.team_members (name, title, photo_url, bio, social_links, display_order, published) VALUES
('John Doe', 'Senior Legal Advisor', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Experienced legal professional with 15+ years in constitutional law.', '{"facebook": "https://facebook.com", "twitter": "https://twitter.com", "linkedin": "https://linkedin.com"}', 1, true),
('Jane Smith', 'Chief of Staff', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Strategic leader managing executive operations and policy coordination.', '{"facebook": "https://facebook.com", "linkedin": "https://linkedin.com"}', 2, true),
('Michael Johnson', 'Communications Director', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Expert in public relations and strategic communications.', '{"twitter": "https://twitter.com", "linkedin": "https://linkedin.com"}', 3, true),
('Sarah Williams', 'Policy Advisor', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Specializes in economic policy and social development initiatives.', '{"linkedin": "https://linkedin.com"}', 4, true);

-- Populate sample testimonials
INSERT INTO public.testimonials (client_name, client_company, client_photo_url, testimonial_text, display_order, featured, published) VALUES
('Robert Chen', 'National Business Association', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200', 'Working with the Vice President''s office has been transformative for our organization. Their commitment to economic development is truly inspiring.', 1, true, true),
('Maria Santos', 'Community Development Foundation', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200', 'The leadership and vision demonstrated by Vice President Rusland has brought real change to our communities. We are grateful for the partnership.', 2, true, true),
('David Thompson', 'Chamber of Commerce', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200', 'An exceptional leader who truly understands the needs of the business community. His policies have created new opportunities for growth.', 3, false, true),
('Lisa Martinez', 'Education Reform Alliance', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200', 'The Vice President''s dedication to educational advancement is remarkable. His initiatives are shaping the future of our nation.', 4, false, true);

-- Populate sample news articles
INSERT INTO public.news (title, slug, content, excerpt, featured_image, category, tags, published, featured, published_at) VALUES
('Vice President Announces New Economic Development Initiative', 'vp-announces-economic-initiative', '<p>Vice President Gregory Allan Rusland today unveiled a comprehensive economic development initiative aimed at strengthening Suriname''s business sector and creating new opportunities for entrepreneurs.</p><p>The initiative includes tax incentives for small businesses, infrastructure improvements, and expanded access to capital for startups. "Our goal is to build a thriving economy that works for all Surinamese people," said VP Rusland.</p><p>Key components of the plan include:</p><ul><li>Streamlined business registration processes</li><li>Investment in digital infrastructure</li><li>Support for local manufacturing</li><li>Enhanced trade partnerships</li></ul>', 'New initiative aims to strengthen business sector and create opportunities for entrepreneurs across Suriname.', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 'Economy', ARRAY['economy', 'business', 'development'], true, true, NOW() - INTERVAL '2 days'),
('VP Rusland Meets with Regional Leaders to Discuss Climate Action', 'vp-climate-action-summit', '<p>In a historic summit held in Paramaribo, Vice President Gregory Allan Rusland convened with regional leaders to address pressing climate challenges facing the Caribbean and South America.</p><p>The two-day conference focused on sustainable development, renewable energy adoption, and climate resilience strategies. "Climate change knows no borders," VP Rusland stated. "We must work together to protect our shared future."</p><p>Participating nations signed a joint declaration committing to:</p><ul><li>Reduce carbon emissions by 30% by 2030</li><li>Invest in renewable energy infrastructure</li><li>Protect rainforest ecosystems</li><li>Share climate technology and research</li></ul>', 'Regional summit brings leaders together to forge unified approach to climate challenges.', 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800', 'Environment', ARRAY['climate', 'environment', 'summit'], true, true, NOW() - INTERVAL '5 days'),
('New Education Programs Launched to Empower Youth', 'education-programs-youth-empowerment', '<p>The Office of the Vice President today launched a series of innovative education programs designed to equip young Surinamese citizens with skills for the 21st century economy.</p><p>"Investing in our youth is investing in our nation''s future," said VP Rusland at the launch ceremony. The programs include coding bootcamps, entrepreneurship training, and leadership development workshops.</p><p>Program highlights:</p><ul><li>Free coding courses for high school students</li><li>Mentorship from successful entrepreneurs</li><li>Scholarships for higher education</li><li>Job placement assistance</li></ul><p>Over 1,000 students are expected to participate in the first year.</p>', 'New initiative provides skills training and opportunities for young people to succeed in modern economy.', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800', 'Education', ARRAY['education', 'youth', 'training'], true, false, NOW() - INTERVAL '1 week');