// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lokofoekwbjjxmzwyasa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxva29mb2Vrd2Jqanhtend5YXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDQ0NjQsImV4cCI6MjA3NTQ4MDQ2NH0.9eCJeM445m0YpSgIgcujh5sXz8nqY5625UFFsnJAFQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});